import { type Empleado } from '~/types/empleados.types';
import { utils as SheetUtils } from 'xlsx';

/**
 * Exports a list of employees into an Excel file
 * @param empleados
 */
export function exportEmpleados(empleados: Empleado[]) {
  const excelContent = [
    [
      'Centro',
      'Apellidos y Nombres',
      'Identificación',
      'Fecha de Nacimiento',
      'Sexo',
      'Estado Civil',
      'Religión',
      'Tiene hijos menores de 6 años de edad',
      'Número de hijos menores de 6 años de edad',
      'Beneficio de guardería',
      'Monto mensual que paga el plantel por guardería',
      'Fecha de ingreso en Centros AVEC',
      'Fecha de ingreso al Plantel',
      'Título',
      'Descripción del Título Acadéimco Obtenido',
      'Mención del Título Académico Obtenido',
      'Carrera que está estudiando',
      'Número de Lapso Académico Aprobado',
      'Postgrado',
      'Tiempo de servicio AVEC',
      'Experiencia Laboral',
      'Grado SISTEMA',
      'Nivel SISTEMA',
      'Grado Centro',
      'Nivel Centro',
      'Cargo',
      'Tiempo en el Cargo',
      'Horas semanales',
      'Sueldo según clasificación',
      'Sueldo SISTEMA',
      'Sueldo Centro',
      'Asignaciones mensual',
      'Deducciones mensual',
      'Prima Antigüedad',
      'Prima Antigüedad según SISTEMA',
      'Beneficio Geográfica',
      'Prima Geográfica',
      'Prima Geográfica según SISTEMA',
      'Prima Compensación Académica',
      'Prima Compensación Académica según SISTEMA',
      'Beneficio de prima por hijo',
      'Cantidad de hijos',
      'Prima por Hijo',
      'Prima por Hijo según SISTEMA',
      'Prima Asistencial',
      'Prima Compensatoria',
      'Contribución por discapacidad',
      'Contribución por discapacidad de hijos',
      'Seguro Social-Regimen prestacional de empleo',
      'Porcentaje SSO',
      'Porcentaje RPE',
      'FAOV',
      'Porcentaje FAOV',
      'Pago directo',
      'Jubilado',
      'Cuenta Bancaria',
      'Observaciones',
      'fecha de registro',
      'fecha de actualización',
    ],
    ...empleados.map((empleado) => [
      '11C058',
      empleado.nombreCompleto,
      empleado.cedula,
      new Date(empleado.fechaNacimiento).toLocaleDateString(),
      empleado.sexo,
      empleado.estadoCivil,
      empleado.religion,
      empleado.hijosMenoresSeis ? 'SI' : 'NO',
      empleado.hijosMenoresSeis,
      empleado.montoMensualGuarderia ? 'SI' : 'NO',
      empleado.montoMensualGuarderia,
      new Date(empleado.fechaIngresoAvec).toLocaleDateString(),
      new Date(empleado.fechaIngresoPlantel).toLocaleDateString(),
      empleado.titulo,
      empleado.descripcionTitulo ?? 'Ninguno',
      empleado.mencionTitulo ?? 'Ninguno',
      empleado.carreraEstudiando ?? 'Ninguno',
      empleado.tipoLapsoEstudios ?? 'Ninguno',
      empleado.numeroLapsosAprobados ?? 'Ninguno',
      empleado.postgrado ?? 'Ninguno',
      new Date().getFullYear() -
        new Date(empleado.fechaIngresoAvec).getFullYear(),
      empleado.experienciaLaboral,
      empleado.gradoSistema,
      empleado.nivelSistema,
      empleado.gradoCentro,
      empleado.nivelCentro,
      empleado.cargo,
      new Date().getFullYear() -
        new Date(empleado.fechaIngresoPlantel).getFullYear(),
      empleado.horasSemanales,
      empleado.sueldo,
      empleado.sueldo,
      empleado.sueldo,
      empleado.asignacionesMensual,
      empleado.deduccionesMensual,
      empleado.primaAntiguedad,
      empleado.primaAntiguedad,
      empleado.primaGeografica ? 'SI' : 'NO',
      empleado.primaGeografica,
      empleado.primaGeografica,
      empleado.primaCompensacionAcademica,
      empleado.primaCompensacionAcademica,
      empleado.cantidadHijos ? 'SI' : 'NO',
      empleado.cantidadHijos,
      empleado.cantidadHijos * 12.5,
      empleado.cantidadHijos * 12.5,
      empleado.primaAsistencial,
      0,
      empleado.contribucionDiscapacidad,
      empleado.contribucionDiscapacidadHijos,
      empleado.porcentajeSso ? 'SI' : 'NO',
      empleado.porcentajeSso,
      empleado.porcentajeRpe,
      empleado.porcentajeFaov ? 'SI' : 'NO',
      empleado.porcentajeFaov,
      empleado.pagoDirecto ? 'SI' : 'NO',
      empleado.jubilado ? 'SI' : 'NO',
      empleado.cuentaBancaria,
      empleado.observaciones ?? '',
      empleado.fechaRegistro,
      empleado.fechaActualizacion,
    ]),
  ];

  const worksheet = SheetUtils.aoa_to_sheet(excelContent);
  const workbook = SheetUtils.book_new();
  SheetUtils.book_append_sheet(workbook, worksheet, 'Empleados');
  return workbook;
}
