PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_empleados` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`cedula` text NOT NULL,
	`nombreCompleto` text NOT NULL,
	`fechaNacimiento` integer NOT NULL,
	`sexo` text NOT NULL,
	`estadoCivil` text NOT NULL,
	`religion` text NOT NULL,
	`hijosMenoresSeis` integer DEFAULT 0 NOT NULL,
	`montoMensualGuarderia` real DEFAULT 0 NOT NULL,
	`fechaIngresoAvec` integer NOT NULL,
	`fechaIngresoPlantel` integer NOT NULL,
	`titulo` integer NOT NULL,
	`descripcionTitulo` text,
	`mencionTitulo` text,
	`carreraEstudiando` text,
	`tipoLapsoEstudios` text,
	`numeroLapsosAprobados` integer,
	`postgrado` text,
	`experienciaLaboral` integer DEFAULT 0 NOT NULL,
	`gradoSistema` integer NOT NULL,
	`nivelSistema` integer NOT NULL,
	`gradoCentro` integer NOT NULL,
	`nivelCentro` integer NOT NULL,
	`cargo` integer NOT NULL,
	`horasSemanales` real NOT NULL,
	`sueldo` real NOT NULL,
	`asignacionesMensual` real DEFAULT 0 NOT NULL,
	`deduccionesMensual` real DEFAULT 0 NOT NULL,
	`primaAntiguedad` real DEFAULT 0 NOT NULL,
	`primaGeografica` real DEFAULT 0 NOT NULL,
	`primaCompensacionAcademica` real DEFAULT 0 NOT NULL,
	`cantidadHijos` integer NOT NULL,
	`primaAsistencial` real DEFAULT 0 NOT NULL,
	`contribucionDiscapacidad` real DEFAULT 0 NOT NULL,
	`contribucionDiscapacidadHijos` real DEFAULT 0 NOT NULL,
	`porcentajeSso` real DEFAULT 0 NOT NULL,
	`porcentajeRpe` real DEFAULT 0 NOT NULL,
	`porcentajeFaov` real DEFAULT 0 NOT NULL,
	`pagoDirecto` integer NOT NULL,
	`jubilado` integer NOT NULL,
	`cuentaBancaria` text NOT NULL,
	`observaciones` text,
	`fechaRegistro` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,
	`fechaActualizacion` integer DEFAULT (cast((julianday('now') - 2440587.5)*86400000 as integer)) NOT NULL,
	FOREIGN KEY (`titulo`) REFERENCES `titulos`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`gradoSistema`) REFERENCES `grados`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`nivelSistema`) REFERENCES `niveles`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`gradoCentro`) REFERENCES `grados`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`nivelCentro`) REFERENCES `niveles`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`cargo`) REFERENCES `cargos`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
INSERT INTO `__new_empleados`("id", "cedula", "nombreCompleto", "fechaNacimiento", "sexo", "estadoCivil", "religion", "hijosMenoresSeis", "montoMensualGuarderia", "fechaIngresoAvec", "fechaIngresoPlantel", "titulo", "descripcionTitulo", "mencionTitulo", "carreraEstudiando", "tipoLapsoEstudios", "numeroLapsosAprobados", "postgrado", "experienciaLaboral", "gradoSistema", "nivelSistema", "gradoCentro", "nivelCentro", "cargo", "horasSemanales", "sueldo", "asignacionesMensual", "deduccionesMensual", "primaAntiguedad", "primaGeografica", "primaCompensacionAcademica", "cantidadHijos", "primaAsistencial", "contribucionDiscapacidad", "contribucionDiscapacidadHijos", "porcentajeSso", "porcentajeRpe", "porcentajeFaov", "pagoDirecto", "jubilado", "cuentaBancaria", "observaciones", "fechaRegistro", "fechaActualizacion") SELECT "id", "cedula", "nombreCompleto", "fechaNacimiento", "sexo", "estadoCivil", "religion", "hijosMenoresSeis", "montoMensualGuarderia", "fechaIngresoAvec", "fechaIngresoPlantel", "titulo", "descripcionTitulo", "mencionTitulo", "carreraEstudiando", "tipoLapsoEstudios", "numeroLapsosAprobados", "postgrado", "experienciaLaboral", "gradoSistema", "nivelSistema", "gradoCentro", "nivelCentro", "cargo", "horasSemanales", "sueldo", "asignacionesMensual", "deduccionesMensual", "primaAntiguedad", "primaGeografica", "primaCompensacionAcademica", "cantidadHijos", "primaAsistencial", "contribucionDiscapacidad", "contribucionDiscapacidadHijos", "porcentajeSso", "porcentajeRpe", "porcentajeFaov", "pagoDirecto", "jubilado", "cuentaBancaria", "observaciones", "fechaRegistro", "fechaActualizacion" FROM `empleados`;--> statement-breakpoint
DROP TABLE `empleados`;--> statement-breakpoint
ALTER TABLE `__new_empleados` RENAME TO `empleados`;--> statement-breakpoint
PRAGMA foreign_keys=ON;--> statement-breakpoint
CREATE UNIQUE INDEX `empleados_cedula_unique` ON `empleados` (`cedula`);