import { integer, real, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const empleados = sqliteTable('empleados', {
  id: integer({ mode: 'number' }).primaryKey({ autoIncrement: true }),
  cedula: text().notNull().unique(),
  nombreCompleto: text().notNull(),
  fechaNacimiento: integer({ mode: 'timestamp' }).notNull(),
  sexo: text({ enum: ['F', 'M'] }).notNull(),
  estadoCivil: text({ enum: ['S', 'C', 'D', 'V', 'R'] }).notNull(),
  religion: text().notNull(),
  hijosMenoresSeis: integer({ mode: 'number' }).default(0).notNull(),
  montoMensualGuarderia: real().default(0).notNull(),
  fechaIngresoAvec: integer({ mode: 'timestamp' }).notNull(),
  fechaIngresoPlantel: integer({ mode: 'timestamp' }).notNull(),
  titulo: text().notNull(),
  descripcionTitulo: text(),
  mencionTitulo: text(),
  carreraEstudiando: text(),
  tipoLapsoEstudios: text(),
  numeroLapsosAprobados: integer({ mode: 'number' }),
  postgrado: text(),
  experienciaLaboral: integer({ mode: 'number' }).default(0).notNull(),
  gradoSistema: text().notNull(),
  nivelSistema: text().notNull(),
  gradoCentro: text().notNull(),
  nivelCentro: text().notNull(),
  cargo: text().notNull(),
  horasSemanales: real().notNull(),
  sueldo: real().notNull(),
  asignacionesMensual: real().default(0).notNull(),
  deduccionesMensual: real().default(0).notNull(),
  primaAntiguedad: real().default(0).notNull(),
  primaGeografica: real().default(0).notNull(),
  primaCompensacionAcademica: real().default(0).notNull(),
  cantidadHijos: integer({ mode: 'number' }).notNull(),
  primaAsistencial: real().default(0).notNull(),
  contribucionDiscapacidad: real().default(0).notNull(),
  contribucionDiscapacidadHijos: real().default(0).notNull(),
  porcentajeSso: real().default(0).notNull(),
  porcentajeRpe: real().default(0).notNull(),
  porcentajeFaov: real().default(0).notNull(),
  pagoDirecto: integer({ mode: 'boolean' }).notNull(),
  jubilado: integer({ mode: 'boolean' }).notNull(),
  cuentaBancaria: text().notNull(),
  observaciones: text(),
  fechaRegistro: integer({ mode: 'timestamp_ms' }).defaultNow().notNull(),
  fechaActualizacion: integer({ mode: 'timestamp_ms' }).defaultNow().notNull(),
});
